{
 "title": "Pulp3 General System Performance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Cloud", "query": "*" },
   { "name": "Node", "query": "$Cloud.*" },
   { "name": "Interface", "query": "$Cloud.$Node.interface-*" },
   { "name": "Disk", "query": "$Cloud.$Node.disk-*" },
   { "name": "cpus0", "query": "$Cloud.$Node.cpu-[0-9]" },
   { "name": "cpus00", "query": "$Cloud.$Node.cpu-[1-9][0-9]" }
  ]
 },
 "panels": [
  {
   "title": "CPU All",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Cloud - $Node - All CPUs",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(averageSeries($Cloud.$Node.cpu-*.cpu-system), 'System')"
      },
      {
       "target": "alias(averageSeries($Cloud.$Node.cpu-*.cpu-user), 'User')"
      },
      {
       "target": "alias(averageSeries($Cloud.$Node.cpu-*.cpu-nice), 'Nice')"
      },
      {
       "target": "alias(averageSeries($Cloud.$Node.cpu-*.cpu-steal), 'Steal')"
      },
      {
       "target": "alias(averageSeries($Cloud.$Node.cpu-*.cpu-softirq), 'SoftIRQ')"
      },
      {
       "target": "alias(averageSeries($Cloud.$Node.cpu-*.cpu-interrupt), 'Interrupt')"
      },
      {
       "target": "alias(averageSeries($Cloud.$Node.cpu-*.cpu-wait), 'Wait')"
      },
      {
       "target": "alias(averageSeries($Cloud.$Node.cpu-*.cpu-idle), 'Idle')"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - All CPUs Sum",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(sumSeries($Cloud.$Node.cpu-*.cpu-system), 'System')"
      },
      {
       "target": "alias(sumSeries($Cloud.$Node.cpu-*.cpu-user), 'User')"
      },
      {
       "target": "alias(sumSeries($Cloud.$Node.cpu-*.cpu-nice), 'Nice')"
      },
      {
       "target": "alias(sumSeries($Cloud.$Node.cpu-*.cpu-steal), 'Steal')"
      },
      {
       "target": "alias(sumSeries($Cloud.$Node.cpu-*.cpu-softirq), 'SoftIRQ')"
      },
      {
       "target": "alias(sumSeries($Cloud.$Node.cpu-*.cpu-interrupt), 'Interrupt')"
      },
      {
       "target": "alias(sumSeries($Cloud.$Node.cpu-*.cpu-wait), 'Wait')"
      },
      {
       "target": "alias(sumSeries($Cloud.$Node.cpu-*.cpu-idle), 'Idle')"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory & Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Cloud - $Node - Memory in Bytes",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias($Cloud.$Node.memory.memory-slab_unrecl, 'Slab Unrecl')"
      },
      {
       "target": "alias($Cloud.$Node.memory.memory-used, 'Used')"
      },
      {
       "target": "alias($Cloud.$Node.memory.memory-buffered, 'Buffered')"
      },
      {
       "target": "alias($Cloud.$Node.memory.memory-slab_recl, 'Slab Recl')"
      },
      {
       "target": "alias($Cloud.$Node.memory.memory-cached, 'Cached')"
      },
      {
       "target": "alias($Cloud.$Node.memory.memory-free, 'Free')"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - Memory in Percentage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(asPercent(#A, #G), 'Slab Unrecl')"
      },
      {
       "target": "alias(asPercent(#B, #G), 'Used')"
      },
      {
       "target": "alias(asPercent(#C, #G), 'Buffered')"
      },
      {
       "target": "alias(asPercent(#D, #G), 'Slab Recl')"
      },
      {
       "target": "alias(asPercent(#E, #G), 'Cached')"
      },
      {
       "target": "alias(asPercent(#F, #G), 'Free')"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - Swap Usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "target": "alias($Cloud.$Node.swap.swap-used, 'Used')"
      },
      {
       "target": "alias($Cloud.$Node.swap.swap-cached, 'Cached')"
      },
      {
       "target": "alias($Cloud.$Node.swap.swap-free, 'Free')"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - Swap IO",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias($Cloud.$Node.swap.swap_io-in, 'In')"
      },
      {
       "target": "alias($Cloud.$Node.swap.swap_io-out, 'Out')"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Cloud - $Node - $Disk iops",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "target": "alias($Cloud.$Node.$Disk.disk_ops.read, 'Read')"
      },
      {
       "target": "alias($Cloud.$Node.$Disk.disk_ops.write, 'Write')"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - $Disk Throughput",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "alias($Cloud.$Node.$Disk.disk_octets.read, 'Read')"
      },
      {
       "target": "alias($Cloud.$Node.$Disk.disk_octets.write, 'Write')"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - $Disk Merged iops",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "target": "alias($Cloud.$Node.$Disk.disk_merged.read, 'Read')"
      },
      {
       "target": "alias($Cloud.$Node.$Disk.disk_merged.write, 'Write')"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - $Disk Pending Operations",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias($Cloud.$Node.$Disk.pending_operations, 'Pending Ops')"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - $Disk Average Time (Estimated)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "alias($Cloud.$Node.$Disk.disk_time.read, 'Read')"
      },
      {
       "target": "alias($Cloud.$Node.$Disk.disk_time.write, 'Write')"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - $Disk IO Time",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(scale($Cloud.$Node.$Disk.disk_io_time.io_time, 0.1), 'Time')"
      },
      {
       "target": "alias($Cloud.$Node.$Disk.disk_io_time.weighted_io_time, 'Weighted Time')"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - / Partition Capacity",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias($Cloud.$Node.df-root.percent_bytes-reserved, 'Reserved')"
      },
      {
       "target": "alias($Cloud.$Node.df-root.percent_bytes-used, 'Used')"
      },
      {
       "target": "alias($Cloud.$Node.df-root.percent_bytes-free, 'Free')"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Cloud - $Node - $Interface Network IO",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "alias($Cloud.$Node.$Interface.if_packets.tx, 'TX')"
      },
      {
       "target": "alias($Cloud.$Node.$Interface.if_packets.rx, 'RX')"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - $Interface Network Throughput",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "alias(scale($Cloud.$Node.$Interface.if_octets.tx, 8), 'TX')"
      },
      {
       "target": "alias(scale($Cloud.$Node.$Interface.if_octets.rx, 8), 'RX')"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - $Interface Errors",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias($Cloud.$Node.$Interface.if_errors.tx, 'TX')"
      },
      {
       "target": "alias($Cloud.$Node.$Interface.if_errors.rx, 'RX')"
      }
     ]
    }
   ]
  },
  {
   "title": "Numa",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Cloud - $Node - Numastat",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasSub(aliasSub($Cloud.$Node.numa-*.vmpage_action-interleave_hit, 'numa-', ''), 'vmpage_action-', ''), 2, 3)"
      },
      {
       "target": "aliasByNode(aliasSub(aliasSub($Cloud.$Node.numa-*.vmpage_action-local_node, 'numa-', ''), 'vmpage_action-', ''), 2, 3)"
      },
      {
       "target": "aliasByNode(aliasSub(aliasSub($Cloud.$Node.numa-*.vmpage_action-numa_foreign, 'numa-', ''), 'vmpage_action-', ''), 2, 3)"
      },
      {
       "target": "aliasByNode(aliasSub(aliasSub($Cloud.$Node.numa-*.vmpage_action-numa_hit, 'numa-', ''), 'vmpage_action-', ''), 2, 3)"
      },
      {
       "target": "aliasByNode(aliasSub(aliasSub($Cloud.$Node.numa-*.vmpage_action-numa_miss, 'numa-', ''), 'vmpage_action-', ''), 2, 3)"
      },
      {
       "target": "aliasByNode(aliasSub(aliasSub($Cloud.$Node.numa-*.vmpage_action-other_node, 'numa-', ''), 'vmpage_action-', ''), 2, 3)"
      }
     ]
    }
   ]
  },
  {
   "title": "IRQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Cloud - $Node - IRQ",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 119 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasSub($Cloud.$Node.irq.irq-[A-Z]*, 'irq-', ''), 3)"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - Interrupts",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 124 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(sumSeries($Cloud.$Node.irq.irq-[0-9]*), 'Interrupts')"
      }
     ]
    }
   ]
  },
  { "title": "Load / Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "$Cloud - $Node - Load Averages / Uptime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias($Cloud.$Node.load.load.shortterm, '1m avg')"
    },
    {
     "target": "alias($Cloud.$Node.load.load.midterm, '5m avg')"
    },
    {
     "target": "alias($Cloud.$Node.load.load.longterm, '15m avg')"
    },
    {
     "target": "alias($Cloud.$Node.uptime.uptime, 'uptime')"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Cloud - $Node - Processes State",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias($Cloud.$Node.processes.ps_state-running, 'Running')"
      },
      {
       "target": "alias($Cloud.$Node.processes.ps_state-stopped, 'Stopped')"
      },
      {
       "target": "alias($Cloud.$Node.processes.ps_state-sleeping, 'Sleeping')"
      },
      {
       "target": "alias($Cloud.$Node.processes.ps_state-blocked, 'Blocked')"
      },
      {
       "target": "alias($Cloud.$Node.processes.ps_state-paging, 'Paging')"
      },
      {
       "target": "alias($Cloud.$Node.processes.ps_state-zombies, 'Zombies')"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - Fork Rate",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias($Cloud.$Node.processes.fork_rate, 'Fork Rate')"
      }
     ]
    }
   ]
  },
  {
   "title": "Pulp3 processes info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of processes and threads",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode($Cloud.$Node.processes-rq_resource_manager.ps_count.*, 2, 4)"
      },
      {
       "target": "aliasByNode($Cloud.$Node.processes-rq_workers.ps_count.*, 2, 4)"
      },
      {
       "target": "aliasByNode($Cloud.$Node.processes-gunicorn.ps_count.*, 2, 4)"
      },
      {
       "target": "aliasByNode($Cloud.$Node.processes-nginx, 2, 4)"
      },
      {
       "target": "aliasByNode($Cloud.$Node.processes-postgres, 2, 4)"
      },
      {
       "target": "aliasByNode($Cloud.$Node.processes-redis-server.ps_count.*, 2, 4)"
      }
     ]
    },
    {
     "title": "CPU time",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "refCount": 3,
       "target": "aliasByNode(divideSeries(scale($Cloud.$Node.processes-rq_resource_manager.ps_cputime.*, 0.0001), #A), 2, 4)",
       "targetFull": "aliasByNode(divideSeries(scale($Cloud.$Node.processes-rq_resource_manager.ps_cputime.*, 0.0001), alias(sumSeries(offset(scale($Cloud.$Node.cpu-*.cpu-idle, 0), 1)), 'cores')), 2, 4)"
      },
      {
       "refCount": 3,
       "target": "aliasByNode(divideSeries(scale($Cloud.$Node.processes-rq_workers.ps_cputime.*, 0.0001), #A), 2, 4)",
       "targetFull": "aliasByNode(divideSeries(scale($Cloud.$Node.processes-rq_workers.ps_cputime.*, 0.0001), alias(sumSeries(offset(scale($Cloud.$Node.cpu-*.cpu-idle, 0), 1)), 'cores')), 2, 4)"
      },
      {
       "refCount": 3,
       "target": "aliasByNode(divideSeries(scale($Cloud.$Node.processes-gunicorn.ps_cputime.*, 0.0001), #A), 2, 4)",
       "targetFull": "aliasByNode(divideSeries(scale($Cloud.$Node.processes-gunicorn.ps_cputime.*, 0.0001), alias(sumSeries(offset(scale($Cloud.$Node.cpu-*.cpu-idle, 0), 1)), 'cores')), 2, 4)"
      },
      {
       "refCount": 2,
       "target": "aliasByNode(divideSeries(scale($Cloud.$Node.processes-nginx.ps_cputime.*, 0.0001), #A), 2, 4)",
       "targetFull": "aliasByNode(divideSeries(scale($Cloud.$Node.processes-nginx.ps_cputime.*, 0.0001), alias(sumSeries(offset(scale($Cloud.$Node.cpu-*.cpu-idle, 0), 1)), 'cores')), 2, 4)"
      },
      {
       "refCount": 2,
       "target": "aliasByNode(divideSeries(scale($Cloud.$Node.processes-redis-server.ps_cputime.*, 0.0001), #A), 2, 4)",
       "targetFull": "aliasByNode(divideSeries(scale($Cloud.$Node.processes-redis-server.ps_cputime.*, 0.0001), alias(sumSeries(offset(scale($Cloud.$Node.cpu-*.cpu-idle, 0), 1)), 'cores')), 2, 4)"
      },
      {
       "refCount": 2,
       "target": "aliasByNode(divideSeries(scale($Cloud.$Node.processes-postgres.ps_cputime.*, 0.0001), #A), 2, 4)",
       "targetFull": "aliasByNode(divideSeries(scale($Cloud.$Node.processes-postgres.ps_cputime.*, 0.0001), alias(sumSeries(offset(scale($Cloud.$Node.cpu-*.cpu-idle, 0), 1)), 'cores')), 2, 4)"
      }
     ]
    },
    {
     "title": "RSS memory",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "target": "aliasByNode($Cloud.$Node.processes-rq_workers.ps_rss, 2)"
      },
      {
       "target": "aliasByNode($Cloud.$Node.processes-rq_resource_manager.ps_rss, 2)"
      },
      {
       "target": "aliasByNode($Cloud.$Node.processes-gunicorn.ps_rss, 2)"
      },
      {
       "target": "aliasByNode($Cloud.$Node.processes-nginx.ps_rss, 2)"
      },
      {
       "target": "aliasByNode($Cloud.$Node.processes-postgres.ps_rss, 2)"
      },
      {
       "target": "aliasByNode($Cloud.$Node.processes-redis-server.ps_rss, 2)"
      }
     ]
    },
    {
     "title": "Disk activity",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "target": "aliasByNode($Cloud.$Node.processes-rq_workers.disk_octets.*, 2, 4)"
      },
      {
       "target": "aliasByNode($Cloud.$Node.processes-rq_resource_manager.disk_octets.*, 2, 4)"
      },
      {
       "target": "aliasByNode($Cloud.$Node.processes-gunicorn.disk_octets.*, 2, 4)"
      },
      {
       "target": "aliasByNode($Cloud.$Node.processes-nginx.disk_octets.*, 2, 4)"
      },
      {
       "target": "aliasByNode($Cloud.$Node.processes-postgres.disk_octets.*, 2, 4)"
      },
      {
       "target": "aliasByNode($Cloud.$Node.processes-redis-server.disk_octets.*, 2, 4)"
      }
     ]
    },
    {
     "title": "Network IO activity",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode($Cloud.$Node.processes-rq_workers.io_octets.*, 2, 4)"
      },
      {
       "target": "aliasByNode($Cloud.$Node.processes-rq_resource_manager.io_octets.*, 2, 4)"
      },
      {
       "target": "aliasByNode($Cloud.$Node.processes-gunicorn.io_octets.*, 2, 4)"
      },
      {
       "target": "aliasByNode($Cloud.$Node.processes-nginx.io_octets.*, 2, 4)"
      },
      {
       "target": "aliasByNode($Cloud.$Node.processes-postgres.io_octets.*, 2, 4)"
      },
      {
       "target": "aliasByNode($Cloud.$Node.processes-redis-server.io_octets.*, 2, 4)"
      }
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Cloud - $Node - Database Sizes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasSub($Cloud.$Node.postgresql-*.pg_db_size, 'postgresql-', ''), 2)"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - Connected Clients",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasSub($Cloud.$Node.postgresql-*.pg_numbackends, 'postgresql-', ''), 2)"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - Foreman Heap/Index/Toast Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasSub($Cloud.$Node.postgresql-foreman.pg_blks-*, 'pg_blks-', ''), 3)"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - Candlepin Heap/Index/Toast Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasSub($Cloud.$Node.postgresql-candlepin.pg_blks-*, 'pg_blks-', ''), 3)"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - Gutterball Heap/Index/Toast Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasSub($Cloud.$Node.postgresql-gutterball.pg_blks-*, 'pg_blks-', ''), 3)"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - Foreman Tuple Operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasSub($Cloud.$Node.postgresql-foreman.pg_n_tup_*, 'pg_n_tup_', ''), 3)"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - Candlepin Tuple Operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasSub($Cloud.$Node.postgresql-candlepin.pg_n_tup_*, 'pg_n_tup_', ''), 3)"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - Gutterball Tuple Operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasSub($Cloud.$Node.postgresql-gutterball.pg_n_tup_*, 'pg_n_tup_', ''), 3)"
      }
     ]
    },
    {
     "title": "$Cloud - $Node - Commits/Rollbacks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(aliasByNode(aliasSub($Cloud.$Node.postgresql-*.pg_xact-commit, 'postgresql-', ''), 2), '$', '-commit')"
      },
      {
       "target": "aliasSub(aliasByNode(aliasSub($Cloud.$Node.postgresql-*.pg_xact-rollback, 'postgresql-', ''), 2), '$', '-rollback')"
      }
     ]
    }
   ]
  }
 ]
}